dubbo:
  application:
    name: search-web
  registry:
    protocol: zookeeper
    address: 192.168.254.128:2181
server:
  port: 9092

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.254.128
    port: 5672
    virtual-host: /zmVirtualHosts
    username: zm
    password: 123456
