dubbo:
  application:
    name: center-web
    qos-port: 33333
  registry:
    protocol: zookeeper
    address: 192.168.254.128:2181

server:
  port: 9090

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.254.128
    port: 5672
    virtual-host: /zmVirtualHosts
    username: zm
    password: 123456

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.254.128:22122

image:
  server: http://192.168.254.128/